# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
Lint/OrAssignmentToConstant:
  Exclude:
    - 'lib/puppet/provider/exec/powershell.rb'

# Offense count: 3
# Configuration parameters: AllowedMethods, AllowedPatterns, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 35

# Offense count: 2
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns, inherit_mode.
# AllowedMethods: refine
Metrics/BlockLength:
  Max: 90

# Offense count: 2
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/CyclomaticComplexity:
  Max: 9

# Offense count: 5
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Max: 17

# Offense count: 2
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/PerceivedComplexity:
  Max: 9

# Offense count: 2
RSpec/AnyInstance:
  Exclude:
    - 'spec/unit/provider/exec/powershell_spec.rb'
    - 'spec/unit/provider/exec/pwsh_spec.rb'

# Offense count: 6
RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'spec/support/**/*.rb'
    - 'spec/acceptance/exec_powershell_spec.rb'
    - 'spec/acceptance/exec_pwsh_spec.rb'

# Offense count: 4
# Configuration parameters: IgnoredMetadata.
RSpec/DescribeClass:
  Exclude:
    - '**/spec/features/**/*'
    - '**/spec/requests/**/*'
    - '**/spec/routing/**/*'
    - '**/spec/system/**/*'
    - '**/spec/views/**/*'
    - 'spec/acceptance/exec_powershell_spec.rb'
    - 'spec/acceptance/exec_pwsh_spec.rb'
    - 'spec/unit/provider/exec/powershell_spec.rb'
    - 'spec/unit/provider/exec/pwsh_spec.rb'

# Offense count: 6
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 25

# Offense count: 15
# Configuration parameters: .
# SupportedStyles: have_received, receive
RSpec/MessageSpies:
  EnforcedStyle: receive

# Offense count: 5
# Configuration parameters: AllowSubject.
RSpec/MultipleMemoizedHelpers:
  Max: 8

# Offense count: 10
# Configuration parameters: AllowedGroups.
RSpec/NestedGroups:
  Max: 4

# Offense count: 38
# Configuration parameters: AllowedPatterns.
# AllowedPatterns: ^expect_, ^assert_
RSpec/NoExpectationExample:
  Exclude:
    - 'spec/acceptance/exec_powershell_spec.rb'
    - 'spec/acceptance/exec_pwsh_spec.rb'

# Offense count: 12
RSpec/RepeatedExample:
  Exclude:
    - 'spec/acceptance/exec_powershell_spec.rb'
    - 'spec/acceptance/exec_pwsh_spec.rb'

# Offense count: 2
RSpec/StubbedMock:
  Exclude:
    - 'spec/unit/provider/exec/powershell_spec.rb'
    - 'spec/unit/provider/exec/pwsh_spec.rb'

# Offense count: 14
RSpec/SubjectStub:
  Exclude:
    - 'spec/unit/provider/exec/powershell_spec.rb'
    - 'spec/unit/provider/exec/pwsh_spec.rb'

# Offense count: 3
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: MinBodyLength, AllowConsecutiveConditionals.
Style/GuardClause:
  Exclude:
    - 'lib/puppet/provider/exec/powershell.rb'
    - 'lib/puppet/provider/exec/pwsh.rb'

# Offense count: 18
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, EnforcedShorthandSyntax, UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
# SupportedShorthandSyntax: always, never, either, consistent
Style/HashSyntax:
  Exclude:
    - 'lib/puppet/provider/exec/powershell.rb'
    - 'lib/puppet/provider/exec/pwsh.rb'
    - 'spec/unit/provider/exec/powershell_spec.rb'
    - 'spec/unit/provider/exec/pwsh_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/IfUnlessModifier:
  Exclude:
    - 'spec/acceptance/exec_pwsh_spec.rb'

# Offense count: 7
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowedMethods, AllowedPatterns.
Style/MethodCallWithoutArgsParentheses:
  Exclude:
    - 'lib/puppet/provider/exec/powershell.rb'
    - 'lib/puppet/provider/exec/pwsh.rb'
    - 'spec/acceptance/exec_powershell_spec.rb'
    - 'spec/acceptance/exec_pwsh_spec.rb'

# Offense count: 1
Style/MixinUsage:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/MultilineTernaryOperator:
  Exclude:
    - 'lib/puppet/provider/exec/pwsh.rb'

# Offense count: 3
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: both, prefix, postfix
Style/NegatedIf:
  Exclude:
    - 'lib/puppet/provider/exec/powershell.rb'
    - 'lib/puppet/provider/exec/pwsh.rb'

# Offense count: 2
# Configuration parameters: AllowedMethods.
# AllowedMethods: respond_to_missing?
Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/puppet/provider/exec/powershell.rb'
    - 'lib/puppet/provider/exec/pwsh.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowSafeAssignment, AllowInMultilineConditions.
Style/ParenthesesAroundCondition:
  Exclude:
    - 'lib/puppet/provider/exec/powershell.rb'
    - 'lib/puppet/provider/exec/pwsh.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: Methods.
Style/RedundantArgument:
  Exclude:
    - 'spec/unit/provider/exec/powershell_spec.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantParentheses:
  Exclude:
    - 'lib/puppet/provider/exec/powershell.rb'
    - 'lib/puppet/provider/exec/pwsh.rb'

# Offense count: 4
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Exclude:
    - 'lib/puppet/provider/exec/powershell.rb'
    - 'lib/puppet/provider/exec/pwsh.rb'

# Offense count: 9
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantStringEscape:
  Exclude:
    - 'lib/puppet/provider/exec/powershell.rb'
    - 'lib/puppet/provider/exec/pwsh.rb'
    - 'spec/acceptance/exec_pwsh_spec.rb'

# Offense count: 6
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Exclude:
    - 'spec/acceptance/exec_pwsh_spec.rb'
    - 'spec/spec_helper.rb'
    - 'spec/unit/provider/exec/powershell_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: implicit, explicit
Style/RescueStandardError:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 2
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: ConvertCodeThatCanStartToReturnNil, AllowedMethods, MaxChainLength.
# AllowedMethods: present?, blank?, presence, try, try!
Style/SafeNavigation:
  Exclude:
    - 'lib/puppet/provider/exec/powershell.rb'
    - 'lib/puppet/provider/exec/pwsh.rb'

# Offense count: 3
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: only_raise, only_fail, semantic
Style/SignalException:
  Exclude:
    - 'lib/puppet/provider/exec/powershell.rb'
    - 'lib/puppet/provider/exec/pwsh.rb'
    - 'spec/acceptance/exec_pwsh_spec.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowModifier.
Style/SoleNestedConditional:
  Exclude:
    - 'lib/puppet/provider/exec/powershell.rb'
    - 'lib/puppet/provider/exec/pwsh.rb'

# Offense count: 2
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: Mode.
Style/StringConcatenation:
  Exclude:
    - 'spec/unit/provider/exec/pwsh_spec.rb'

# Offense count: 41
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'spec/acceptance/exec_powershell_spec.rb'
    - 'spec/acceptance/exec_pwsh_spec.rb'
    - 'spec/spec_helper_acceptance_local.rb'
    - 'spec/unit/provider/exec/powershell_spec.rb'
    - 'spec/unit/provider/exec/pwsh_spec.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: AllowMethodsWithArguments, AllowedMethods, AllowedPatterns, AllowComments.
# AllowedMethods: define_method
Style/SymbolProc:
  Exclude:
    - 'spec/unit/provider/exec/powershell_spec.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInArrayLiteral:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInHashLiteral:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/UnlessElse:
  Exclude:
    - 'lib/puppet/provider/exec/powershell.rb'

# Offense count: 15
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, AllowedPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 203
